@ 'C:\Users\labsfiap\Desktop\ORACLE\SCRIPT_MODELO_PEDIDO(1).SQL'

ALTER TABLE PEDIDO ADD STATUS VARCHAR2(30);
ALTER TABLE CIDADE MODIFY NOM_CIDADE VARCHAR2(50);

INSERT INTO PAIS SELECT * FROM PF1788.PAIS;
COMMIT;
INSERT INTO ESTADO SELECT * FROM PF1788.ESTADO;
COMMIT;
INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
COMMIT;
INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
COMMIT;
INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
COMMIT;
INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
COMMIT;
INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
COMMIT;
INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
COMMIT;
INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
COMMIT;
INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
COMMIT;
INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
COMMIT;
INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
COMMIT;
INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
COMMIT;
INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
COMMIT;
INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
COMMIT;
INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
COMMIT;
INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
COMMIT;
INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;
COMMIT;

SELECT * FROM PEDIDO;
SELECT * FROM ITEM_PEDIDO;