CREATE TABLE pais (
    cod_pais NUMERIC PRIMARY KEY,
    nome_pais VARCHAR2(30)
)

ALTER TABLE pais MODIFY
    nome_pais VARCHAR(30) NOT NULL;

CREATE TABLE estado (
    cod_estado NUMERIC PRIMARY KEY,
    nome_estado VARCHAR2(30),
    cod_pais NUMERIC
)

ALTER TABLE estado MODIFY
    nome_estado VARCHAR2(30) NOT NULL;

ALTER TABLE estado
    ADD CONSTRAINT fk_estado FOREIGN KEY ( cod_pais )
        REFERENCES pais ( cod_pais );
        
CREATE TABLE cidade (
    cod_cidade  NUMERIC PRIMARY KEY,
    nome_cidade VARCHAR2(30),
    cod_estado  NUMERIC
)

ALTER TABLE cidade MODIFY
    nome_cidade VARCHAR2(30) NOT NULL;

ALTER TABLE cidade
    ADD CONSTRAINT fk_cidade FOREIGN KEY ( cod_estado )
        REFERENCES estado ( cod_estado );
        
CREATE TABLE bairro (
    cod_bairro NUMERIC PRIMARY KEY,
    nome_bairro VARCHAR2(30) NOT NULL,
    cod_cidade NUMERIC
)

ALTER TABLE bairro
    ADD CONSTRAINT fk_bairro FOREIGN KEY ( cod_cidade )
        REFERENCES cidade ( cod_cidade );
        
CREATE TABLE endereco_cliente (
    cod_endereco NUMERIC PRIMARY KEY,
    numero NUMERIC,
    cep NUMERIC,
    referencia VARCHAR2(30),
    logradouro VARCHAR2(30),
    cod_bairro NUMERIC,
    cod_cliente NUMERIC
)

ALTER TABLE endereco_cliente
    ADD CONSTRAINT fk_endereco FOREIGN KEY ( cod_bairro )
        REFERENCES bairro ( cod_bairro );
        
ALTER TABLE endereco_cliente
    ADD CONSTRAINT fk_cliente FOREIGN KEY ( cod_cliente )
        REFERENCES cliente ( cod_cliente );
        
ALTER TABLE endereco_cliente MODIFY
    logradouro VARCHAR2(30) NOT NULL;
        
CREATE TABLE cliente (
    cod_cliente NUMERIC PRIMARY KEY,
    nome VARCHAR2(30) NOT NULL
)

ALTER TABLE cliente
    ADD CONSTRAINT fkDD_endereco FOREIGN KEY ( cod_cliente )
        REFERENCES endereco_cliente ( cod_endereco );
        
CREATE TABLE cliente_jurica (
    cod_pessoa_ju NUMERIC PRIMARY KEY,
    cnpj          NUMERIC,
    ie            NUMERIC,
    cod_cliente   NUMERIC,
    FOREIGN KEY ( cod_cliente )
        REFERENCES cliente ( cod_cliente )
)

CREATE TABLE genero (
    cod_genero NUMERIC PRIMARY KEY,
    descricao VARCHAR2(30) NOT NULL
)

CREATE TABLE cliente_fisico (
    cod_cliente_fisico NUMERIC PRIMARY KEY,
    cpf                NUMERIC,
    cod_cliente        NUMERIC,
    cod_genero         NUMERIC,
    FOREIGN KEY ( cod_cliente )
        REFERENCES cliente ( cod_cliente ),
    FOREIGN KEY ( cod_genero )
        REFERENCES genero ( cod_genero )
)

CREATE TABLE cargo (
    cod_cargo NUMERIC,
    nome VARCHAR2(30) NOT NULL
)

ALTER TABLE cargo ADD PRIMARY KEY ( cod_cargo );

CREATE TABLE funcionario (
    cod_funcionario NUMERIC PRIMARY KEY,
    nome            VARCHAR2(30) NOT NULL,
    data_cadastro   DATE,
    cod_cargo       NUMERIC,
    cod_gestor      NUMERIC
)

ALTER TABLE funcionario
    ADD CONSTRAINT fk_cargo FOREIGN KEY ( cod_cargo )
        REFERENCES cargo ( cod_cargo );
        
ALTER TABLE funcionario
    ADD CONSTRAINT fk_gestor FOREIGN KEY ( cod_gestor )
        REFERENCES funcionario ( cod_funcionario );
        
CREATE TABLE pedido (
    cod_pedido         NUMERIC PRIMARY KEY,
    data               DATE,
    cod_cliente_fisico NUMERIC,
    cod_cliente        NUMERIC,
    cod_genero         NUMERIC,
    cod_funcionario    NUMERIC,
    cod_pessoa_ju      NUMERIC,
    FOREIGN KEY ( cod_cliente_fisico )
        REFERENCES cliente_fisico ( cod_cliente_fisico ),
    FOREIGN KEY ( cod_cliente )
        REFERENCES cliente ( cod_cliente ),
    FOREIGN KEY ( cod_genero )
        REFERENCES genero ( cod_genero ),
    FOREIGN KEY ( cod_funcionario )
        REFERENCES funcionario ( cod_funcionario ),
    FOREIGN KEY ( cod_pessoa_ju )
        REFERENCES cliente_jurica ( cod_pessoa_ju )
)

CREATE TABLE tipo (
    cod_tipo NUMERIC PRIMARY KEY,
    descricao VARCHAR2(40)
)

CREATE TABLE produto (
    cod_produto NUMERIC PRIMARY KEY,
    descricao   VARCHAR2(40),
    cod_tipo    NUMERIC,
    FOREIGN KEY (cod_tipo )
    REFERENCES tipo ( cod_tipo )
)

CREATE TABLE item_pedido (
    quantidade     NUMERIC(10),
    valor_unitario NUMERIC(10),
    valor_total    NUMERIC(10),
    cod_pedido     NUMERIC,
    cod_produto    NUMERIC,
    FOREIGN KEY ( cod_pedido )
        REFERENCES pedido ( cod_pedido ),
    FOREIGN KEY ( cod_produto )
        REFERENCES produto ( cod_produto )
)

-- EXERCICIO COLOCAR 5 REGISTROS EM CADA TABELA

CREATE SEQUENCE SQ_AULA_DDL; -- INCREMENT BY VALOR
CREATE SEQUENCE SQ_AULA_DDL2;

INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (1, 'BRASIL');

-- TABLE PAIS
INSERT INTO PAIS (COD_PAIS, NOME_PAIS) VALUES (SQ_AULA_DDL.NEXTVAL, 'BRASIL');
COMMIT;
INSERT INTO PAIS (COD_PAIS, NOME_PAIS) VALUES (SQ_AULA_DDL.NEXTVAL, 'ARGENTINA');
COMMIT;
INSERT INTO PAIS (COD_PAIS, NOME_PAIS) VALUES (SQ_AULA_DDL.NEXTVAL, 'ALEMANHA');
COMMIT;
INSERT INTO PAIS (COD_PAIS, NOME_PAIS) VALUES (SQ_AULA_DDL.NEXTVAL, 'BULGARIA');
COMMIT;
INSERT INTO PAIS (COD_PAIS, NOME_PAIS) VALUES (SQ_AULA_DDL.NEXTVAL, 'PORTUGAL');
COMMIT;

SELECT * FROM PAIS;

-- TABLE BAIRRO
INSERT INTO BAIRRO (COD_BAIRRO, NOME_BAIRRO) VALUES (SQ_AULA_DDL.NEXTVAL, 'ACLIMACAO');
COMMIT;
INSERT INTO BAIRRO (COD_BAIRRO, NOME_BAIRRO) VALUES (SQ_AULA_DDL.NEXTVAL, 'PAULISTA');
COMMIT;
INSERT INTO BAIRRO (COD_BAIRRO, NOME_BAIRRO) VALUES (SQ_AULA_DDL.NEXTVAL, 'VILA MARIANA');
COMMIT;
INSERT INTO BAIRRO (COD_BAIRRO, NOME_BAIRRO) VALUES (SQ_AULA_DDL.NEXTVAL, 'SAO MATEUS');
COMMIT;
INSERT INTO BAIRRO (COD_BAIRRO, NOME_BAIRRO) VALUES (SQ_AULA_DDL.NEXTVAL, 'PENHA');
COMMIT;

SELECT * FROM BAIRRO;

-- TABLE CARGO
INSERT INTO CARGO (COD_CARGO, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'DESENVOLVEDOR');
COMMIT;
INSERT INTO CARGO (COD_CARGO, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'ANALISTA');
COMMIT;
INSERT INTO CARGO (COD_CARGO, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'ENGENHEIRO DE SOFTWARE');
COMMIT;
INSERT INTO CARGO (COD_CARGO, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'CIENTISTA DE DADOS');
COMMIT;
INSERT INTO CARGO (COD_CARGO, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'SUPORTE DE TI');
COMMIT;

SELECT * FROM CARGO;

-- TABLE CIDADE
INSERT INTO CIDADE (COD_CIDADE, NOME_CIDADE) VALUES (SQ_AULA_DDL.NEXTVAL, 'SAO PAULO');
COMMIT;
INSERT INTO CIDADE (COD_CIDADE, NOME_CIDADE) VALUES (SQ_AULA_DDL.NEXTVAL, 'GUARULHOS');
COMMIT;
INSERT INTO CIDADE (COD_CIDADE, NOME_CIDADE) VALUES (SQ_AULA_DDL.NEXTVAL, 'RIO DE JANEIRO');
COMMIT;
INSERT INTO CIDADE (COD_CIDADE, NOME_CIDADE) VALUES (SQ_AULA_DDL.NEXTVAL, 'COPACABANA');
COMMIT;
INSERT INTO CIDADE (COD_CIDADE, NOME_CIDADE) VALUES (SQ_AULA_DDL.NEXTVAL, 'SALVADOR');
COMMIT;

SELECT * FROM CIDADE;

-- TABLE CLIENTE
INSERT INTO CLIENTE (COD_CLIENTE, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'PEDRO');
COMMIT;
INSERT INTO CLIENTE (COD_CLIENTE, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'MATHEUS');
COMMIT;
INSERT INTO CLIENTE (COD_CLIENTE, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'SAMIRA');
COMMIT;
INSERT INTO CLIENTE (COD_CLIENTE, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'YASMIN');
COMMIT;
INSERT INTO CLIENTE (COD_CLIENTE, NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'GUILHERME');
COMMIT;

SELECT * FROM CLIENTE;

-- TABLE CLIENTE FISICO
INSERT INTO CLIENTE_FISICO (COD_CLIENTE_FISICO, CPF) VALUES (SQ_AULA_DDL.NEXTVAL, 2334455);
COMMIT;
INSERT INTO CLIENTE_FISICO (COD_CLIENTE_FISICO, CPF) VALUES (SQ_AULA_DDL.NEXTVAL, 5555555);
COMMIT;
INSERT INTO CLIENTE_FISICO (COD_CLIENTE_FISICO, CPF) VALUES (SQ_AULA_DDL.NEXTVAL, 6666666);
COMMIT;
INSERT INTO CLIENTE_FISICO (COD_CLIENTE_FISICO, CPF) VALUES (SQ_AULA_DDL.NEXTVAL, 7777777);
COMMIT;
INSERT INTO CLIENTE_FISICO (COD_CLIENTE_FISICO, CPF) VALUES (SQ_AULA_DDL.NEXTVAL, 8888888);
COMMIT;

SELECT * FROM CLIENTE_FISICO;

-- TABLE CLIENTE JURIDICO
INSERT INTO CLIENTE_JURICA (COD_PESSOA_JU, CNPJ) VALUES (SQ_AULA_DDL.NEXTVAL, 00019999);
COMMIT;
INSERT INTO CLIENTE_JURICA (COD_PESSOA_JU, CNPJ) VALUES (SQ_AULA_DDL.NEXTVAL, 9898787);
COMMIT;
INSERT INTO CLIENTE_JURICA (COD_PESSOA_JU, CNPJ) VALUES (SQ_AULA_DDL.NEXTVAL, 23234543);
COMMIT;
INSERT INTO CLIENTE_JURICA (COD_PESSOA_JU, CNPJ) VALUES (SQ_AULA_DDL.NEXTVAL, 4534543);
COMMIT;
INSERT INTO CLIENTE_JURICA (COD_PESSOA_JU, CNPJ) VALUES (SQ_AULA_DDL.NEXTVAL, 6767456);
COMMIT;

SELECT * FROM CLIENTE_JURICA;

-- TABLE ENDERECO_CLIENTE
INSERT INTO ENDERECO_CLIENTE (COD_ENDERECO, LOGRADOURO) VALUES (SQ_AULA_DDL.NEXTVAL, 'RUA FILHO DO CEU');
COMMIT;
INSERT INTO ENDERECO_CLIENTE (COD_ENDERECO, LOGRADOURO) VALUES (SQ_AULA_DDL.NEXTVAL, 'RUA  ALMEIDA DE ANDRE');
COMMIT;
INSERT INTO ENDERECO_CLIENTE (COD_ENDERECO, LOGRADOURO) VALUES (SQ_AULA_DDL.NEXTVAL, 'AVENIDA LINS');
COMMIT;
INSERT INTO ENDERECO_CLIENTE (COD_ENDERECO, LOGRADOURO) VALUES (SQ_AULA_DDL.NEXTVAL, 'VASCONSCELOS');
COMMIT;
INSERT INTO ENDERECO_CLIENTE (COD_ENDERECO, LOGRADOURO) VALUES (SQ_AULA_DDL.NEXTVAL, 'RUA PEDRO SAMPAIO');
COMMIT;

SELECT * FROM ENDERECO_CLIENTE;

-- TABLE ESTADO
INSERT INTO ESTADO (COD_ESTADO,NOME_ESTADO) VALUES (SQ_AULA_DDL.NEXTVAL, 'SP');
COMMIT;
INSERT INTO ESTADO (COD_ESTADO,NOME_ESTADO) VALUES (SQ_AULA_DDL.NEXTVAL, 'RJ');
COMMIT;
INSERT INTO ESTADO (COD_ESTADO,NOME_ESTADO) VALUES (SQ_AULA_DDL.NEXTVAL, 'BA');
COMMIT;
INSERT INTO ESTADO (COD_ESTADO,NOME_ESTADO) VALUES (SQ_AULA_DDL.NEXTVAL, 'TO');
COMMIT;
INSERT INTO ESTADO (COD_ESTADO,NOME_ESTADO) VALUES (SQ_AULA_DDL.NEXTVAL, 'MG');
COMMIT;

SELECT * FROM ESTADO;

-- TABLE FUNCIONARIO
INSERT INTO FUNCIONARIO (COD_FUNCIONARIO,NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'PEDRO');
COMMIT;
INSERT INTO FUNCIONARIO (COD_FUNCIONARIO,NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'NELMA');
COMMIT;
INSERT INTO FUNCIONARIO (COD_FUNCIONARIO,NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'ANTONIO');
COMMIT;
INSERT INTO FUNCIONARIO (COD_FUNCIONARIO,NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'NICOLAS');
COMMIT;
INSERT INTO FUNCIONARIO (COD_FUNCIONARIO,NOME) VALUES (SQ_AULA_DDL.NEXTVAL, 'SAMUEL');
COMMIT;

SELECT * FROM FUNCIONARIO;

-- TABLE GENERO
INSERT INTO GENERO (COD_GENERO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'MASCULINO');
COMMIT;
INSERT INTO GENERO (COD_GENERO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'FEMININO');
COMMIT;
INSERT INTO GENERO (COD_GENERO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'FEMININO');
COMMIT;
INSERT INTO GENERO (COD_GENERO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'MASCULINO');
COMMIT;
INSERT INTO GENERO (COD_GENERO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'MASCULINO');
COMMIT;

SELECT * FROM GENERO;

-- TABLE ITEM_PEDIDO
INSERT INTO ITEM_PEDIDO (COD_PEDIDO,VALOR_UNITARIO) VALUES (SQ_AULA_DDL.NEXTVAL, 20);
COMMIT;
INSERT INTO ITEM_PEDIDO (COD_PEDIDO,VALOR_UNITARIO) VALUES (SQ_AULA_DDL.NEXTVAL, 20);
COMMIT;
INSERT INTO ITEM_PEDIDO (COD_PEDIDO,VALOR_UNITARIO) VALUES (SQ_AULA_DDL.NEXTVAL, 20);
COMMIT;
INSERT INTO ITEM_PEDIDO (COD_PEDIDO,VALOR_UNITARIO) VALUES (SQ_AULA_DDL.NEXTVAL, 20);
COMMIT;
INSERT INTO ITEM_PEDIDO (COD_PEDIDO,VALOR_UNITARIO) VALUES (SQ_AULA_DDL.NEXTVAL, 20);
COMMIT;

SELECT * FROM ITEM_PEDIDO;

-- TABLE PEDIDO
INSERT INTO PEDIDO (COD_PEDIDO,DATA) VALUES (SQ_AULA_DDL.NEXTVAL, '19-02-2025');
COMMIT;
INSERT INTO PEDIDO (COD_PEDIDO,DATA) VALUES (SQ_AULA_DDL.NEXTVAL, '18-02-2025');
COMMIT;
INSERT INTO PEDIDO (COD_PEDIDO,DATA) VALUES (SQ_AULA_DDL.NEXTVAL, '17-02-2025');
COMMIT;
INSERT INTO PEDIDO (COD_PEDIDO,DATA) VALUES (SQ_AULA_DDL.NEXTVAL, '16-02-2025');
COMMIT;
INSERT INTO PEDIDO (COD_PEDIDO,DATA) VALUES (SQ_AULA_DDL.NEXTVAL, '15-02-2025');
COMMIT;

SELECT * FROM PEDIDO;

-- TABLE PRODUTO
INSERT INTO PRODUTO (COD_PRODUTO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'PRODUTO MUITO LEGAL');
COMMIT;
INSERT INTO PRODUTO (COD_PRODUTO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'PRODUTO MUITO LEGAL');
COMMIT;
INSERT INTO PRODUTO (COD_PRODUTO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'PRODUTO MUITO LEGAL');
COMMIT;
INSERT INTO PRODUTO (COD_PRODUTO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'PRODUTO MUITO LEGAL');
COMMIT;
INSERT INTO PRODUTO (COD_PRODUTO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 'PRODUTO MUITO LEGAL');
COMMIT;

SELECT * FROM PRODUTO;

-- TABLE TIPO
INSERT INTO TIPO (COD_TIPO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 909090);
COMMIT;
INSERT INTO TIPO (COD_TIPO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 909090);
COMMIT;
INSERT INTO TIPO (COD_TIPO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 909090);
COMMIT;
INSERT INTO TIPO (COD_TIPO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 909090);
COMMIT;
INSERT INTO TIPO (COD_TIPO,DESCRICAO) VALUES (SQ_AULA_DDL.NEXTVAL, 909090);
COMMIT;

SELECT * FROM TIPO;



